//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistant.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assistant.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 GTA:WORLD中国社区聊天日志解析助手 编辑：Ciscaux 
        ///已安装版本: {0} {1}
        ///目录: {2} 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级过滤器 的本地化字符串。
        /// </summary>
        internal static string AdvancedFilter {
            get {
                return ResourceManager.GetString("AdvancedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 因为 &quot;{0}&quot; 目录已经存在。 的本地化字符串。
        /// </summary>
        internal static string AlreadyExistingDirectoriesWarning {
            get {
                return ResourceManager.GetString("AlreadyExistingDirectoriesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在试图禁用自动启动功能时发生了一个错误。 的本地化字符串。
        /// </summary>
        internal static string AutoStartDisableError {
            get {
                return ResourceManager.GetString("AutoStartDisableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在试图启用自动启动功能时发生了一个错误。 的本地化字符串。
        /// </summary>
        internal static string AutoStartEnableError {
            get {
                return ResourceManager.GetString("AutoStartEnableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果你删除或将分析器移到不同的位置，这个功能将停止工作。 的本地化字符串。
        /// </summary>
        internal static string AutoStartWarning {
            get {
                return ResourceManager.GetString("AutoStartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在试图自动保存聊天记录时发生了错误。
        ///
        ///请确保你选择了一个非系统的目录作为你的备份路径。 的本地化字符串。
        /// </summary>
        internal static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在将备份文件转移到新目录时发生了错误。 的本地化字符串。
        /// </summary>
        internal static string BackupMoveError {
            get {
                return ResourceManager.GetString("BackupMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动备份: {0} 的本地化字符串。
        /// </summary>
        internal static string BackupStatus {
            get {
                return ResourceManager.GetString("BackupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动备份已被关闭，如果你想使用它，请重新设置。 的本地化字符串。
        /// </summary>
        internal static string BackupTurnedOff {
            get {
                return ResourceManager.GetString("BackupTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当设置对话框打开时，自动备份功能将被关闭，只有当您关闭设置对话框时，新的设置才会被应用。
        ///
        ///您想继续吗？ 的本地化字符串。
        /// </summary>
        internal static string BackupWillBeOff {
            get {
                return ResourceManager.GetString("BackupWillBeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个非根目录作为你的备份目录位置。 的本地化字符串。
        /// </summary>
        internal static string BadBackupPath {
            get {
                return ResourceManager.GetString("BadBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个有效的备份位置或关闭自动备份。 的本地化字符串。
        /// </summary>
        internal static string BadBackupPathSave {
            get {
                return ResourceManager.GetString("BadBackupPathSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请为你的RAGEMP目录位置选择一个非根目录。 的本地化字符串。
        /// </summary>
        internal static string BadDirectoryPath {
            get {
                return ResourceManager.GetString("BadDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 b 的本地化字符串。
        /// </summary>
        internal static string BetaShort {
            get {
                return ResourceManager.GetString("BetaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 个字符和{1} 行 的本地化字符串。
        /// </summary>
        internal static string CharacterCounter {
            get {
                return ResourceManager.GetString("CharacterCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前时间: {0} 的本地化字符串。
        /// </summary>
        internal static string CurrentTime {
            get {
                return ResourceManager.GetString("CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动发现你的RAGEMP目录在 {0}
        ///
        ///如果这不正确或你有多个RAGEMP安装，请手动浏览正确的路径。 的本地化字符串。
        /// </summary>
        internal static string DirectoryFinder {
            get {
                return ResourceManager.GetString("DirectoryFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在试图自动查找你的RAGEMP目录位置时发生了错误，请手动浏览。 的本地化字符串。
        /// </summary>
        internal static string DirectoryFinderError {
            get {
                return ResourceManager.GetString("DirectoryFinderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法检测到你的RAGEMP目录的路径，请手动寻找目录。 的本地化字符串。
        /// </summary>
        internal static string DirectoryFinderNotFound {
            get {
                return ResourceManager.GetString("DirectoryFinderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息(首次启动) 的本地化字符串。
        /// </summary>
        internal static string DirectoryFinderTitle {
            get {
                return ResourceManager.GetString("DirectoryFinderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://face.gta-world.cn/ 的本地化字符串。
        /// </summary>
        internal static string FacebrowserLink {
            get {
                return ResourceManager.GetString("FacebrowserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://forum.gta-world.cn/ 的本地化字符串。
        /// </summary>
        internal static string FeatureShowcaseLink {
            get {
                return ResourceManager.GetString("FeatureShowcaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在试图删除该文件时发生了错误。 的本地化字符串。
        /// </summary>
        internal static string FileDeleteError {
            get {
                return ResourceManager.GetString("FileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果您想过滤您的聊天记录，每行只能有一个单词、数字或有效名称对。
        ///例如：船，500美元，约翰，无名氏或John_Doe 的本地化字符串。
        /// </summary>
        internal static string FilterHint {
            get {
                return ResourceManager.GetString("FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到匹配的。
        ///
        ///请确保每行只有一个单词、数字或有效的名称对。
        ///例如：船，500美元，约翰，无名氏或John_Doe 的本地化字符串。
        /// </summary>
        internal static string FilterHintNoMatches {
            get {
                return ResourceManager.GetString("FilterHintNoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在过滤操作中跳过了一个或多个字，因为它们不是有效的格式。
        ///
        ///请确保每行只有一个单词、数字或有效的名称对。
        ///例如：船，500美元，约翰，无名氏或John_Doe 的本地化字符串。
        /// </summary>
        internal static string FilterHintSkipped {
            get {
                return ResourceManager.GetString("FilterHintSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聊天记录{0} 加载{1} 的本地化字符串。
        /// </summary>
        internal static string FilterLogStatus {
            get {
                return ResourceManager.GetString("FilterLogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取所选文件时发生了一个错误。 的本地化字符串。
        /// </summary>
        internal static string FilterReadError {
            get {
                return ResourceManager.GetString("FilterReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://forum.gta-world.cn/ 的本地化字符串。
        /// </summary>
        internal static string ForumsLink {
            get {
                return ResourceManager.GetString("ForumsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在游戏运行时自动备份聊天记录 (每{0}{1}) 的本地化字符串。
        /// </summary>
        internal static string IntervalHint {
            get {
                return ResourceManager.GetString("IntervalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}(推荐) 的本地化字符串。
        /// </summary>
        internal static string IntervalRecommended {
            get {
                return ResourceManager.GetString("IntervalRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的RAGEMP目录路径。 的本地化字符串。
        /// </summary>
        internal static string InvalidDirectoryPath {
            get {
                return ResourceManager.GetString("InvalidDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在尝试启用自动备份之前，请选择一个有效的RAGEMP目录位置。 的本地化字符串。
        /// </summary>
        internal static string InvalidDirectoryPathBackup {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在尝试过滤您的聊天记录之前，请选择一个有效的RAGEMP目录位置。 的本地化字符串。
        /// </summary>
        internal static string InvalidDirectoryPathFilter {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选语言将用于从正确的服务器提取聊天记录。
        ///
        ///这意味着，如果您选择了中文，您将只能解析从中文服务器上生成的聊天记录。如果您想解析其他聊天记录，您将需要改变应用程序的语言。 的本地化字符串。
        /// </summary>
        internal static string LanguageInfo {
            get {
                return ResourceManager.GetString("LanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  于{0} 的本地化字符串。
        /// </summary>
        internal static string LoadedAt {
            get {
                return ResourceManager.GetString("LoadedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 45.125.44.121_22005 的本地化字符串。
        /// </summary>
        internal static string MainIP {
            get {
                return ResourceManager.GetString("MainIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭解析器将阻止自动备份的发生。
        ///
        ///你想把分析器最小化到系统托盘中吗？ 的本地化字符串。
        /// </summary>
        internal static string MinimizeInsteadOfClose {
            get {
                return ResourceManager.GetString("MinimizeInsteadOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        internal static string MinutePlural {
            get {
                return ResourceManager.GetString("MinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        internal static string MinuteSingular {
            get {
                return ResourceManager.GetString("MinuteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你想把你现有的所有备份文件移到新的目录中吗？ 的本地化字符串。
        /// </summary>
        internal static string MoveBackups {
            get {
                return ResourceManager.GetString("MoveBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现有多个GTA:WORLD的资源目录。建议你使用一个IP连接到服务器并删除其他资源目录。
        ///
        ///保留其中一个 &quot;{0}&quot; 或 &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string MultipleChatLogs {
            get {
                return ResourceManager.GetString("MultipleChatLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string Negation {
            get {
                return ResourceManager.GetString("Negation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到GTA:WORLD的聊天记录。 的本地化字符串。
        /// </summary>
        internal static string NoChatLog {
            get {
                return ResourceManager.GetString("NoChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你还没有加载聊天记录。 的本地化字符串。
        /// </summary>
        internal static string NoChatLogLoaded {
            get {
                return ResourceManager.GetString("NoChatLogLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到更新。
        ///尝试检查您的互联网连接或在设置窗口中增加更新检查超时。
        ///
        ///已安装的版本: {0} 的本地化字符串。
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你还没有过滤任何东西。 的本地化字符串。
        /// </summary>
        internal static string NothingFiltered {
            get {
                return ResourceManager.GetString("NothingFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有移动任何目录到新的位置 的本地化字符串。
        /// </summary>
        internal static string NothingMovedWarning {
            get {
                return ResourceManager.GetString("NothingMovedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你还没有解析出任何东西。 的本地化字符串。
        /// </summary>
        internal static string NothingParsed {
            get {
                return ResourceManager.GetString("NothingParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你还没有输入任何要过滤的词。
        ///
        ///如果你不想过滤单词，请使用简易过滤器。 的本地化字符串。
        /// </summary>
        internal static string NoWordsToFilter {
            get {
                return ResourceManager.GetString("NoWordsToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在解析聊天记录时检测到一种旧格式，建议你删除它和所有其他没有正确更新的脚本。
        ///
        ///你想删除这些文件吗？
        ///(在删除前会对聊天记录文件进行解析) 的本地化字符串。
        /// </summary>
        internal static string OldChatLog {
            get {
                return ResourceManager.GetString("OldChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你想打开在GTA:World论坛上找到的聊天记录解析器的文档页面吗？ 的本地化字符串。
        /// </summary>
        internal static string OpenDocumentation {
            get {
                return ResourceManager.GetString("OpenDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另一个应用已经在运行，检查你的任务栏或任务管理器。 的本地化字符串。
        /// </summary>
        internal static string OtherInstanceRunning {
            get {
                return ResourceManager.GetString("OtherInstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在解析聊天记录时发生错误。 的本地化字符串。
        /// </summary>
        internal static string ParseError {
            get {
                return ResourceManager.GetString("ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只将 &quot;{0}&quot; 目录移至新的位置 的本地化字符串。
        /// </summary>
        internal static string PartialMoveWarning {
            get {
                return ResourceManager.GetString("PartialMoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://gitee.com/Ciscaux/GTAWCN-Log-Parser 的本地化字符串。
        /// </summary>
        internal static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题 的本地化字符串。
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://gitee.com/Ciscaux/GTAWCN-Log-Parser/releases 的本地化字符串。
        /// </summary>
        internal static string ReleasesLink {
            get {
                return ResourceManager.GetString("ReleasesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您正在运行最新版本的聊天记录解析器。
        ///
        ///安装的版本: {0} 的本地化字符串。
        /// </summary>
        internal static string RunningLatest {
            get {
                return ResourceManager.GetString("RunningLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同一聊天记录被备份了 {0} 次或更多，这意味着负责记录您的聊天记录的Ragemp客户端脚本已经损坏。
        ///
        ///这种情况在你失去网络连接或服务器崩溃时发生。唯一已知的解决方法是删除你所玩的服务器的资源目录。
        ///
        ///丢失的聊天记录是无法恢复的。 的本地化字符串。
        /// </summary>
        internal static string SameHashWarning {
            get {
                return ResourceManager.GetString("SameHashWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在试图保存文件时发生了一个错误。 的本地化字符串。
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 play.gta-world.cn_22005 的本地化字符串。
        /// </summary>
        internal static string SecondaryIP {
            get {
                return ResourceManager.GetString("SecondaryIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string SecondPlural {
            get {
                return ResourceManager.GetString("SecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第二 的本地化字符串。
        /// </summary>
        internal static string SecondSingular {
            get {
                return ResourceManager.GetString("SecondSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有在你关闭设置对话框后，设置才会被应用。 的本地化字符串。
        /// </summary>
        internal static string SettingsAfterClose {
            get {
                return ResourceManager.GetString("SettingsAfterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简易过滤 的本地化字符串。
        /// </summary>
        internal static string SimpleFilter {
            get {
                return ResourceManager.GetString("SimpleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功解析并备份了聊天记录至 {0} 的本地化字符串。
        /// </summary>
        internal static string SuccessfulBackup {
            get {
                return ResourceManager.GetString("SuccessfulBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析器需要重新启动，以便切换到选定的服务器。
        ///
        ///你想现在就应用这些变化并重新启动应用程序吗？ 的本地化字符串。
        /// </summary>
        internal static string SwitchServer {
            get {
                return ResourceManager.GetString("SwitchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://ucp.gta-world.cn/ 的本地化字符串。
        /// </summary>
        internal static string UCPLink {
            get {
                return ResourceManager.GetString("UCPLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}. 的本地化字符串。
        /// </summary>
        internal static string UpdateAbortTime {
            get {
                return ResourceManager.GetString("UpdateAbortTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聊天记录解析器的新版本现在可以在Gitee上使用。安装版本: {0}
        ///可用版本: {1}
        ///
        ///你想现在访问发布页面吗？ 的本地化字符串。
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用的更新 的本地化字符串。
        /// </summary>
        internal static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}{1} 的本地化字符串。
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
